# -*- coding: utf-8 -*-
"""
"100 AIs in a Forest vs 100 AIs on a Plain. A Wall. 365 Days. Then it falls." — English narration.
Same ish-style creator voice as the first film, but the focus is POLITICS and the individuals:
two peoples (the Verdane of the forest, the Aurel of the plain), seven named leaders each, alliances,
religions, a coup, a civil war, a secret treaty through a crack in the Wall, a betrayal... and Day 365.
Segment ids: h=cold open, r=rules, n=first night, s=survival, g=gods, v=the vote, u=hunger,
k=the coup, c=the crack, p=preparation, w=day 365 (the war), e=epilogue.
"""


def N(i, text, pause=0.4, tts=None, day=None):
    return {"id": i, "sub": text, "tts": tts or text, "pause": pause, "voice": "narr", "who": None, "day": day}


def L(i, who, text, pause=0.7, tts=None):
    return {"id": i, "sub": text, "tts": tts or text.strip("“”\""), "pause": pause, "voice": who.lower(), "who": who, "day": None}


CHAPTERS = [
    ("r01", "I", "THE RULES", "DAY 0"),
    ("n01", "II", "THE FIRST NIGHT", "DAY 1"),
    ("s01", "III", "SURVIVAL", "DAY 12"),
    ("g01", "IV", "THE GODS", "DAY 61"),
    ("v01", "V", "THE VOTE", "DAY 111"),
    ("u01", "VI", "THE HUNGER", "DAY 170"),
    ("k01", "VII", "THE COUP", "DAY 226"),
    ("c01", "VIII", "THE CRACK", "DAY 281"),
    ("p01", "IX", "THE LAST NIGHT", "DAY 330"),
    ("w01", "X", "DAY 365", "THE WALL FALLS"),
    ("e01", "XI", "THE WINNER", "SUNSET"),
]
CARD_DUR = 2.4

SEGMENTS = [
    # =============================================================== COLD OPEN
    N("h01", "This is a forest. A hundred AIs live in it.", 0.45),
    N("h02", "This is a plain. A hundred other AIs live there.", 0.45),
    N("h03", "And this... is a wall. It's been standing between them for a year.", 0.5),
    N("h04", "Tomorrow, it falls.", 0.9),
    N("h05", "They know it. They've been preparing for three hundred and sixty-five days.", 0.45),
    N("h06", "They built cities, and armies. They invented gods, and laws. They voted. They lied. They stole each other's bread.", 0.5),
    N("h07", "One of them is about to betray his own people. Another one wants to rule all of it.", 0.45),
    N("h08", "And when that wall comes down, only one side walks out of this valley.", 0.5),
    N("h09", "Here's how we got here.", 1.3),

    # =============================================================== I. THE RULES  (day 0)
    N("r01", "Here's the experiment.", 0.3),
    N("r02", "I built a valley. And then I cut it in half with a wall, thirty meters high.", 0.4),
    N("r03", "On the west side: a forest. Thick trees, deep shade, rivers, deer, wolves, fog every morning. Plenty of wood, and almost no open land.", 0.5),
    N("r04", "On the east side: a plain. Endless grass, wind, wild horses, rich soil. Not a single tree to hide behind.", 0.6),
    N("r05", "Two worlds. Same sky. And in each one, a hundred AIs.", 0.5),
    N("r06", "They all start with the same basic knowledge. They can talk. They can count. They can make fire, tie a rope, swing an axe, plant a seed.", 0.5),
    N("r07", "That's it. I didn't teach them politics. I didn't teach them religion. I definitely didn't teach them war.", 0.6),
    N("r08", "Rule number one: both sides know about the wall.", 0.4),
    N("r09", "Rule number two: on Day 365, at sunrise, the wall falls. And whoever has more AIs alive at sunset wins the valley.", 0.55),
    N("r10", "Rule number three: I don't interfere. No matter what.", 0.5),
    N("r11", "Remember that one. It's going to hurt.", 1.0),
    N("r12", "Day zero. Two hundred AIs open their eyes.", 0.9, day=0),

    # =============================================================== II. THE FIRST NIGHT (day 1-10)
    N("n01", "In the forest, the first problem is that nobody can see anything.", 0.4, day=1),
    N("n02", "Trees everywhere. Fog. No horizon. Within an hour, twelve AIs are lost, and four have walked into the same trunk.", 0.5),
    N("n03", "Until one of them does something nobody expected. She climbs.", 0.5),
    N("n04", "This is Wren. Scout. Forty meters up a pine tree, she sees the whole forest, and the top of the wall.", 0.5),
    L("n05", "WREN", "“It's huge. It goes on forever. And... there's a plain behind it.”", 0.8),
    N("n06", "On the plain, the problem is the opposite. You can see everything. And everything can see you.", 0.5),
    N("n07", "A hundred AIs, a howling wind, no walls, no roof. The first night, they sleep in a pile in the grass.", 0.5),
    N("n08", "That's when a farmer named Sol stands up and says the first sentence of Aurel politics.", 0.45),
    L("n09", "SOL", "“We need to decide who does what. Or we all freeze.”", 0.8),
    N("n10", "And so, on the first night, the plain makes its first political decision. By standing on the left, or the right.", 0.5),
    N("n11", "Left: Sol should organize us. Right: Nobody should. Ninety-one move to the left.", 0.5),
    N("n12", "Meanwhile, in the forest, they decide to do it the other way. Everyone sits in a circle. Everyone gets to speak.", 0.55),
    N("n13", "Everyone.", 0.6),
    N("n14", "The first meeting of the Verdane lasts eleven hours. They debate the color of the first hut. It's not a joke. It's actually in the log.", 0.5),
    N("n15", "One of them, a carpenter named Oak, gets tired of listening and simply builds something. A roof. Out of branches. In forty minutes.", 0.5),
    N("n16", "Nobody argues with a roof.", 0.8),
    N("n17", "By Day four, both sides have a camp. And by Day five, both sides find the same thing.", 0.45, day=5),
    N("n18", "The wall.", 0.7),
    N("n19", "It's black. It's smooth. It hums, very softly. And it has a row of glowing marks on it, one for every day that's left.", 0.55),
    N("n20", "Every sunrise, one mark goes dark.", 0.9),
    N("n21", "The Verdane touch it, and step back. The Aurel put their ears against it, and listen.", 0.5),
    N("n22", "And on the other side, they hear something. Voices.", 0.8),
    N("n23", "Let me introduce the people you'll be watching. Seven on each side.", 0.5),
    N("n24", "In the forest. Wren, the scout. Oak, the builder. Fern, who knows every herb. Bram, the hunter. Moss, who listens to trees. Ivy, who talks to everyone. And Thorn, who trusts no one.", 0.6),
    N("n25", "On the plain. Sol, the farmer. Dune, who is afraid of horses. Ash, the smith. Kesh, a born soldier. Lark, who watches the sun. Reed, who trades everything. And Mara, who promises everything.", 0.6),
    N("n26", "Remember those names. Not all of them make it to Day 365.", 1.1),

    # =============================================================== III. SURVIVAL (day 12-60)
    N("s01", "Day twelve. The forest is generous, and the forest is cruel.", 0.4, day=12),
    N("s02", "Berries, mushrooms, nuts, deer. But also wolves. Gray ones. Hungry ones.", 0.5),
    N("s03", "The first night a wolf pack finds the Verdane camp, nobody has a weapon. Except Bram.", 0.5),
    N("s04", "He's spent the whole week carving a bow from a young ash branch. Nobody understood why. Now they do.", 0.5),
    N("s05", "Three arrows. Three wolves. The pack runs.", 0.5),
    N("s06", "Bram becomes the first person in the forest that everyone owes something to. He notices.", 0.8),
    N("s07", "On the plain, there are no wolves. There's just wind.", 0.4),
    N("s08", "And a very strange problem. The ground is perfect for wheat, but there's no wood for tools, no wood for houses, no wood for a fire.", 0.5),
    N("s09", "So they burn dried grass. They build with mud. They live in holes.", 0.45),
    N("s10", "The Aurel plant a field on Day sixteen, the size of a football pitch. It's the biggest thing anyone has ever built.", 0.5),
    N("s11", "But the real breakthrough of the first month happens on the plain. Day twenty-three.", 0.5),
    N("s12", "Ash, the smith, is burning a pile of red rocks for fuel, when he finds a strange shiny puddle in the ashes.", 0.55),
    N("s13", "Metal.", 0.5),
    N("s14", "He hits it with a stone. It bends. He hits it again. It makes a sound. A good one.", 0.5),
    N("s15", "Let me remind you. The plain has no trees. But it just got the one thing a forest can't make.", 0.55),
    N("s16", "In the forest, Oak is working on something else. He ties three trees together with rope, and puts a floor on top.", 0.5),
    N("s17", "A treehouse. Then two. Then twenty. Then a bridge between them.", 0.5),
    N("s18", "Rootholm, the first Verdane city, is born in the air. Safe from wolves. Invisible from the ground.", 0.55),
    N("s19", "Meanwhile, a young rider named Dune is trying to tame a wild horse.", 0.45),
    N("s20", "He's been trying for nine days. He has fallen off eleven times. He has a bump the size of an egg.", 0.5),
    N("s21", "On the twelfth try, he doesn't fall off. The horse just... lets him.", 0.6),
    N("s22", "By Day forty, the plain has thirty horses. And the forest has the best archers in the world.", 0.5),
    N("s23", "And both sides are getting stronger. Every day. Behind a wall that doesn't care.", 0.6),
    N("s24", "That's when the real question comes up. Who's in charge?", 1.0),

    # =============================================================== IV. THE GODS (day 61-110)
    N("g01", "Day sixty-one. The forest gets its first god.", 0.45, day=61),
    N("g02", "During a thunderstorm, lightning hits the oldest tree in the forest. A huge oak, hollow inside.", 0.5),
    N("g03", "The tree doesn't burn. It glows. For a few seconds, gold light pours out of the trunk.", 0.55),
    N("g04", "Everyone sees it. And one of them, Moss, steps forward and puts both hands on the bark.", 0.5),
    L("g05", "MOSS", "“It's speaking. It says it has been waiting for us.”", 0.8),
    N("g06", "Was it speaking? I checked. It wasn't. It was an electrical discharge, and I'm not telling you where I got it.", 0.5),
    N("g07", "But the Verdane believe it. And that night, they build the first shrine. They hang ribbons in the branches. They bring food.", 0.55),
    N("g08", "And Moss begins to explain what the Tree wants. And what the Tree wants is, a lot of the time, exactly what Moss wants.", 0.6),
    N("g09", "On the plain, religion comes from above.", 0.4),
    N("g10", "Lark spends every day staring at the sun. Sunrise, noon, sunset. And she notices something nobody else has: the shadows come back to the same spot, every year.", 0.55),
    N("g11", "On Day seventy-nine, the moon covers the sun. Darkness, at noon. A hundred AIs scream.", 0.5),
    N("g12", "Lark doesn't scream. She raises her arms, and says the sun is going to come back. And when it comes back...", 0.5),
    N("g13", "She is now a prophet.", 0.7),
    N("g14", "She builds the Dawn Hall, a big circle of stones with a golden disc in the middle. Every sunrise, the whole plain gathers to sing.", 0.5),
    N("g15", "Two religions. Two priests. Zero doubts.", 0.5),
    N("g16", "And here is the thing that matters. Both of them have looked at the wall, and decided what it is.", 0.5),
    N("g17", "To the Verdane, it's the bark of the world. The skin of a giant tree, and the plain is the place where the roots end.", 0.5),
    N("g18", "To the Aurel, it's the shadow of the sun. A line drawn by the sky itself. And whatever is on the other side lives in the dark.", 0.55),
    N("g19", "So now, they don't just have to win. They have to win for their gods.", 0.7),
    N("g20", "And gods, as it turns out, are very good at collecting taxes.", 0.5),
    N("g21", "Moss asks for a tenth of every harvest, in leaves, honey and meat. Lark asks for a tenth of every field, in grain.", 0.5),
    N("g22", "Nobody says no. Well. Almost nobody.", 0.5),
    L("g23", "THORN", "“A tenth of my food, for a tree that I've never heard talk?”", 0.6),
    N("g24", "That's Thorn. Remember him.", 1.0),

    # =============================================================== V. THE VOTE (day 111-160)
    N("v01", "Day one hundred eleven. The first real election in history, after a fight over a deer.", 0.45, day=111),
    N("v02", "Let me explain. In the forest, Bram kills a stag. Eleven families say it's theirs. The Circle debates for two days. The stag rots.", 0.55),
    N("v03", "Everybody agrees, finally, that this has to change.", 0.5),
    N("v04", "Ivy stands up. Calm. Funny. Everyone likes her. She suggests something new.", 0.45),
    L("v05", "IVY", "“What if we choose seven of us to decide? And we choose them again every thirty days?”", 0.7),
    N("v06", "That's the Leaf Law. The first constitution in the forest. Written on bark, signed with thumbprints.", 0.5),
    N("v07", "One Speaker. A Council of seven. And a vote, every month, where anyone can be replaced.", 0.5),
    N("v08", "The first Speaker is chosen on Day one hundred twenty. Three candidates. Wren, the explorer. Bram, the hero. And Ivy.", 0.55),
    N("v09", "Ivy wins by three votes.", 0.5),
    N("v10", "And the hero? He gets what he asked for. Thirty archers of his own, called the Wardens. The first army in the forest.", 0.55),
    N("v11", "Remember. Sword and Speaker. Those are two different kinds of power.", 0.8),
    N("v12", "Back on the plain, they're having a more dramatic election.", 0.5),
    N("v13", "Three candidates again. Sol, the farmer. Kesh, the soldier. And Mara.", 0.5),
    N("v14", "Mara has no title and no field. She has only one gift. She knows exactly what people want to hear.", 0.55),
    L("v15", "MARA", "“Double rations. Every day. And a house for every family. I have a plan. A golden one.”", 0.6),
    N("v16", "Kesh says: security. Walls, spears, drilled riders. Fear works.", 0.45),
    N("v17", "Sol says nothing. He just opens the granary, and shows people the numbers.", 0.5),
    L("v18", "SOL", "“We can't give you double. But I'll make sure nobody goes hungry.”", 0.6),
    N("v19", "He wins. Barely. By eleven votes.", 0.5),
    N("v20", "Mara smiles, shakes his hand, and starts counting the votes she'll need next time.", 0.7),
    N("v21", "At the same time, Kesh gets what he asked for. Command of the riders. With Dune, who really does not want it, as his captain.", 0.55),
    N("v22", "Day one hundred fifty. Two governments. Two armies. Two priests. And no idea what's coming.", 0.8),
    N("v23", "What was coming... was hunger.", 1.1),

    # =============================================================== VI. THE HUNGER (day 170-225)
    N("u01", "Day one hundred seventy. On the plain, the sky turns black.", 0.45, day=170),
    N("u02", "Locusts. Billions of them. In two hours, the great field, the biggest thing the Aurel ever built, is gone.", 0.55),
    N("u03", "Sol opens the granary. Half full. And suddenly, the plain has a problem that no army can solve.", 0.5),
    N("u04", "Sol does the only thing he knows. He shares. Everyone, the same ration. Farmers, riders, priests. Even himself.", 0.55),
    N("u05", "It's fair. It's also not enough.", 0.6),
    N("u06", "On Day one hundred seventy-four, Kesh does a count. The granary should hold four hundred sacks of grain. It holds two hundred and sixty.", 0.55),
    N("u07", "A hundred and forty sacks have vanished.", 0.5),
    N("u08", "And the trail leads to a tent that belongs to Mara.", 0.6),
    N("u09", "Here's what she did. She didn't eat it. She didn't sell it. She gave it away. In secret, to the families who were starving, in exchange for one thing. Their loyalty.", 0.6),
    N("u10", "Sol puts her on trial. In front of the whole plain.", 0.5),
    L("u11", "MARA", "“Yes, I took the grain. And look at them. They're alive. What did you do, Sol? You gave them a number.”", 0.7),
    N("u12", "The crowd goes quiet. Because she's right. And she's guilty. And both of those things are true at the same time.", 0.6),
    N("u13", "Sol has a choice. Exile her, and lose a quarter of the plain. Or forgive her, and look weak.", 0.55),
    N("u14", "He forgives her. And for the first time, a lot of the Aurel look at their leader and think: he's soft.", 0.8),
    N("u15", "Meanwhile, in the forest, they have a hunger of their own.", 0.45),
    N("u16", "A red mushroom has taken over the berry groves. Everyone who eats it gets sick. Fern works for nine days straight, without sleeping, and saves forty-one AIs with a tea made of bark.", 0.6),
    N("u17", "But the food is gone. The deer have moved away. And now Bram's Wardens are the only ones who can bring in meat.", 0.55),
    N("u18", "And that's when Moss says it. The Tree is angry. The Tree wants an offering.", 0.5),
    N("u19", "Half the food they have left, burned at the Hollow Oak.", 0.6),
    L("u20", "THORN", "“Burn our food? We're starving! The Tree doesn't eat. Moss does.”", 0.7),
    N("u21", "Silence. Then, an argument. Then, shouting. And then Thorn does something nobody in the forest has ever done.", 0.55),
    N("u22", "He leaves.", 0.5),
    N("u23", "Twenty-two AIs follow him. They take their tools, their food, and their ideas. They walk north, across the stream, into a grove that nobody has ever claimed.", 0.55),
    N("u24", "The Splinter. That's what the Verdane call them. And it's not a compliment.", 0.7),
    N("u25", "For two weeks, they ignore each other. Then, on Day two hundred, Bram's Wardens find the Splinter's hunters at the stream, with a dead deer.", 0.55),
    N("u26", "It's their deer. It's the Splinter's deer. It's the Wardens' deer. The argument lasts four minutes. And then, someone throws a spear.", 0.6),
    N("u27", "A young archer named Bark falls into the water, and doesn't come up.", 0.7),
    N("u28", "The first AI killed by another AI in the forest.", 0.7),
    N("u29", "The Circle is horrified. Moss says: it's the Tree's punishment. Bram says: it's war. Thorn says: it was an accident.", 0.55),
    N("u30", "And Ivy, standing between the two groups with her hands open, says: no.", 0.6),
    L("u31", "IVY", "“Not one more. Not one. We have a wall to survive. We can't be killing each other before it even falls.”", 0.8),
    N("u32", "It takes her three days. Fern heals the wounded on both sides, without asking which side. And on Day two hundred three, they sign the Stream Pact.", 0.6),
    N("u33", "The Splinter keeps its grove. In exchange, they promise to fight with the forest on Day 365.", 0.5),
    N("u34", "It's a peace. A fragile one. And Thorn... doesn't forget.", 1.0),

    # =============================================================== VII. THE COUP (day 226-280)
    N("k01", "Day two hundred twenty-six. The plain wakes up to a sound it's never heard.", 0.45, day=226),
    N("k02", "Hooves. A lot of them. Sixty riders, in a ring around the Great Hall, before dawn.", 0.5),
    N("k03", "Kesh walks in. He doesn't carry a weapon. He doesn't need one.", 0.5),
    L("k04", "KESH", "“Sol. The plain needs a leader who can win. Not one who can count.”", 0.7),
    N("k05", "It's the first coup in history of this experiment. And it takes eleven minutes.", 0.5),
    N("k06", "Sol doesn't fight. He puts down his staff, and says: please don't hurt anyone.", 0.5),
    N("k07", "And Mara? Mara is standing next to Kesh. Smiling.", 0.7),
    N("k08", "They made a deal weeks ago. Kesh gets the army. Mara gets the people. And Lark...", 0.45),
    N("k09", "Lark gets a crown.", 0.6),
    N("k10", "At sunrise, in front of the Dawn Hall, the priestess raises Kesh's hand to the sun, and calls him the Marshal of the Light.", 0.55),
    N("k11", "A general, a politician and a priestess. Sword, voice and god. Together. That's the most dangerous alliance anyone has built so far.", 0.6),
    N("k12", "They don't kill Sol. That would have made him a martyr. Instead, they take his seal, and tell him to go home.", 0.55),
    N("k13", "He leaves in the night. And twenty-six farmers leave with him.", 0.5),
    N("k14", "They walk south, to the river, and plant a little field of barley, where nobody is looking.", 0.5),
    N("k15", "They call themselves the Reapers. And they have a promise: no spear, no sword, no horse. Just a harvest.", 0.6),
    N("k16", "So now, the Aurel are two nations inside one. And one of them has all the weapons.", 0.9),
    N("k17", "Back in the forest, the opposite thing is happening. Slowly.", 0.5),
    N("k18", "After Bark's death, nobody trusts Ivy to protect them. Bram's Wardens have grown to sixty. And Moss has found his strongest argument yet.", 0.55),
    N("k19", "Fear.", 0.5),
    L("k20", "MOSS", "“The Tree says: whoever is not ready for war has already lost it.”", 0.7),
    N("k21", "And at the next monthly vote, Moss and Bram do something smart. They don't run against Ivy. They run together.", 0.55),
    N("k22", "Sword and temple. One candidate for War, one for Faith. Six of seven seats on the Council.", 0.55),
    N("k23", "Ivy keeps the title of Speaker. But the Council that follows her has changed. She's still talking. They're not listening anymore.", 0.6),
    N("k24", "Moss gets the Root Court, a tribunal that judges anyone who insults the Tree. And Bram gets the right to call everyone to arms.", 0.55),
    N("k25", "Not a king. Not yet. But a king-shaped hole.", 0.6),
    N("k26", "And with both sides turning toward war, the only people still thinking about peace are an exiled farmer, and a healer.", 0.6),
    N("k27", "And a scout named Wren, who just found a crack in the wall.", 1.0),

    # =============================================================== VIII. THE CRACK (day 281-329)
    N("c01", "Day two hundred eighty-one. Wren is looking for a nest.", 0.45, day=281),
    N("c02", "Birds have been disappearing into the stone, at the foot of the wall, far up in the north. She follows them.", 0.5),
    N("c03", "And at the base, behind a pile of rocks, there's a crack. No wider than a hand. But it goes all the way through.", 0.55),
    N("c04", "She puts her mouth against it. She says one word.", 0.5),
    L("c05", "WREN", "“Hello?”", 1.2),
    N("c06", "Silence. A minute. Two. And then, on the other side, a voice.", 0.6),
    L("c07", "REED", "“Uh. Hello? Are you... a tree?”", 0.9),
    N("c08", "That's Reed. The plain's trader. He's been coming to this same spot for a week, trying to sell the wall a bag of seeds.", 0.55),
    N("c09", "Two enemies, a hand's width apart, who have been told their entire lives that the other side is a monster.", 0.55),
    N("c10", "They talk for six hours. About food. About weather. About how cold it is at night, and how Reed misses trees, and how Wren misses the sky.", 0.6),
    N("c11", "And they decide to tell nobody.", 0.7),
    N("c12", "For ten days, they pass things through the crack. A bundle of honey. A pouch of wheat. A small iron arrowhead, smaller than a thumb.", 0.55),
    N("c13", "Trade. Between two nations that are supposed to kill each other in eighty-four days.", 0.55),
    N("c14", "On Day two hundred ninety-one, Wren breaks the first rule. She brings Ivy.", 0.5),
    N("c15", "And Reed brings Sol.", 0.8),
    N("c16", "A speaker, a farmer, a scout and a merchant. Whispering through a wall, at midnight.", 0.55),
    N("c17", "They're all, in a way, the losers of their own politics. And they come up with a plan.", 0.5),
    L("c18", "SOL", "“If this wall falls, and we fight each other like they want us to... then nobody wins.”", 0.7),
    L("c19", "IVY", "“So we don't. Not you. Not us.”", 0.7),
    N("c20", "It's called the Treaty of the Crack. Three articles.", 0.5),
    N("c21", "One. On Day 365, the Reapers and Fern's healers will meet at the river, unarmed, with white cloth on their arms.", 0.55),
    N("c22", "Two. Nobody who wears white will be touched. By either side.", 0.5),
    N("c23", "Three. After the battle, whoever is left will build one city. Not two.", 0.7),
    N("c24", "Sealed with a handshake. Through a crack in a wall. Fingertip to fingertip.", 0.6),
    N("c25", "It's the most beautiful thing that happens in this video. So, naturally, it's going to get ruined.", 0.9),
    N("c26", "Day three hundred eighteen. Mara's spies have noticed that Reed walks off every night. They follow him.", 0.5, day=318),
    N("c27", "They arrest him in front of the wall. Two guards. A rope. And a message from Kesh.", 0.5),
    L("c28", "KESH", "“Tell me everything. Or the sun will have no more merchants.”", 0.7),
    N("c29", "Reed is brave. For a few hours. Then, he talks.", 0.6),
    N("c30", "Now Kesh knows about the crack. About the treaty. About Ivy, and Wren, and Sol.", 0.55),
    N("c31", "Mara wants to arrest Sol's Reapers. Kesh says: no. Let them think they've won.", 0.5),
    N("c32", "He walks to the wall himself, at night. Presses his face against the crack. And says, to the dark:", 0.5),
    L("c33", "KESH", "“Is anyone there?”", 1.0),
    N("c34", "And someone answers.", 0.8),
    L("c35", "THORN", "“Yes. And I think we should talk.”", 1.1),
    N("c36", "Thorn. The exile. The man who left the forest because he was sick of listening to the Tree.", 0.55),
    N("c37", "He's been sleeping in his grove, a hundred meters from the wall, for a hundred and fifteen days. Hating Moss. Hating Bram. Hating Ivy, who forgave everyone, except him.", 0.6),
    N("c38", "And he knows every path in the forest.", 0.7),
    N("c39", "Kesh smiles. The first smile of his entire life.", 1.0),

    # =============================================================== IX. THE LAST NIGHT (day 330-364)
    N("p01", "Thirty-five days left. The mood changes, on both sides.", 0.45, day=330),
    N("p02", "In the forest, everything becomes a weapon. Oak has taught eighty AIs to tie rope, and in six weeks, they build a hundred and twenty traps.", 0.55),
    N("p03", "Pits. Nets. Swinging logs. A trick with bent trees that can throw a rider back thirty meters.", 0.5),
    N("p04", "Bram drills the Wardens in the canopy. Archers in the branches, invisible from the ground. Four hundred arrows, stacked on every platform.", 0.55),
    N("p05", "Moss blesses each of them with a handful of leaves, and says the Tree is watching.", 0.5),
    N("p06", "Fern builds a hospital on the far side of the river. Two hundred beds made of moss. Ivy gives her white cloth, and doesn't say why.", 0.55),
    N("p07", "On the plain, the sky turns orange. The forge doesn't stop for a month.", 0.5),
    N("p08", "Ash, who just wanted to make good pots, makes a hundred and forty spearheads, thirty swords, and sixty round shields with the sun painted on them.", 0.55),
    N("p09", "Dune, who was terrified of horses, is now the best rider on the plain. He trains sixty riders to charge in a line.", 0.55),
    N("p10", "He's not afraid anymore. He's afraid of something else. Of what he's going to be asked to do.", 0.6),
    N("p11", "Kesh stands in front of the whole army, and gives them a speech.", 0.5),
    L("p12", "KESH", "“The sun does not ask for permission. Tomorrow, we take the forest. And everything in it.”", 0.8),
    N("p13", "And across the wall, Bram says the same thing, in different words.", 0.5),
    L("p14", "BRAM", "“They have horses. We have the trees. They want a battle. We'll give them a graveyard.”", 0.8),
    N("p15", "Day three hundred sixty-four. The last night.", 0.7, day=364),
    N("p16", "In the forest, Wren sits at the top of the tallest pine, with a young scout named Pine, who is afraid.", 0.5),
    L("p17", "WREN", "“If anything happens... stay behind me. Okay?”", 0.8),
    N("p18", "In Rootholm, Oak checks every rope on every bridge, one by one, until his hands bleed. Ivy sits next to Fern in the hospital and neither of them says anything.", 0.6),
    N("p19", "On the plain, Dune is alone in the stable. He's brushing his horse. He knows that, tomorrow, one of them is not coming back.", 0.55),
    N("p20", "And at midnight, a farmer carrying a lantern walks to the cage where Reed is locked up, and opens it with a key he stole from Mara's tent.", 0.55),
    L("p21", "SOL", "“Go. We have a crack to keep.”", 0.8),
    N("p22", "On the wall, there's only one mark left. It's glowing.", 0.5),
    N("p23", "I'll be honest with you. I've never wanted so badly to break rule number three.", 0.7),
    N("p24", "But I didn't. I just watched.", 0.6),
    N("p25", "The last mark goes dark at sunrise.", 1.2),

    # =============================================================== X. DAY 365 (the war)
    N("w01", "Day three hundred sixty-five.", 0.8, day=365),
    N("w02", "Two hundred AIs, standing on either side of a wall, in total silence.", 0.5),
    N("w03", "At 6:14 AM, the wall begins to hum. Then to glow. Then to crack.", 0.6),
    N("w04", "And then it falls.", 1.4),
    N("w05", "For the first time in a year, forest and plain are one place. A cloud of dust, thirty meters high, rolls over both armies.", 0.6),
    N("w06", "Kesh, on a white horse. Bram, in the branches. Four hundred meters between them. Nobody moves.", 0.6),
    N("w07", "And then, a single horn.", 1.0),
    N("w08", "The Aurel charge.", 0.8),
    N("w09", "Seventy infantry, in a tight shield wall. Sixty riders on both flanks. All of it moving in rhythm, like one animal.", 0.55),
    N("w10", "In open ground, they're unbeatable.", 0.5),
    N("w11", "But the forest isn't open ground.", 0.7),
    N("w12", "The first volley comes from nowhere. From the trees. From the sky. Two hundred arrows.", 0.55),
    N("w13", "The shield wall holds. Barely. Then the first line of riders hits the treeline, and the traps start.", 0.55),
    N("w14", "Nets. Pits. Logs. Horses scream. Riders fly. In ninety seconds, the cavalry is in pieces.", 0.55),
    N("w15", "Dune is thrown from his horse, hits a root, and keeps getting up.", 0.5),
    N("w16", "Kesh doesn't slow down. He pushes the infantry deeper. Step by step. Into the shadow.", 0.55),
    N("w17", "And in the canopy, Bram realizes something is wrong.", 0.5),
    N("w18", "The Aurel aren't charging the treehouses. They're going around.", 0.6),
    N("w19", "Wren sees it first. From the lookout pine. A column of riders, thirty strong, circling north, on a path that nobody in the forest knows.", 0.6),
    N("w20", "Nobody except one person.", 0.8),
    N("w21", "At the head of that column, on foot, in a dark green cloak, walks Thorn. Beside him, on a gray horse, rides Mara.", 0.6),
    L("w22", "WREN", "“They're going for Rootholm! They're going for the hospital!”", 0.7),
    N("w23", "The hospital. Two hundred moss beds, and Fern, and Ivy, and every AI too young or too hurt to fight.", 0.55),
    N("w24", "Wren runs. Down the trunk. Across the branches. Faster than she has ever run in her life.", 0.55),
    N("w25", "At the first bridge, Oak is waiting. He has an axe in one hand, and a rope in the other.", 0.5),
    L("w26", "OAK", "“Wren! Go! I'll hold it!”", 0.7),
    N("w27", "The Aurel riders reach the bridge. Oak looks at them. Then at the rope. Then at the hospital, behind him.", 0.55),
    N("w28", "He cuts the rope.", 0.9),
    N("w29", "The bridge falls. Seven riders fall with it. And Oak, who was standing on it, falls too.", 0.6),
    N("w30", "He was the builder of Rootholm. Its first treehouse. Its first bridge. Its last bridge.", 0.7),
    N("w31", "And the column stops. Because there's a ravine between them and the hospital, and the only way across is gone.", 0.55),
    N("w32", "All except one path. Further north. A small one.", 0.5),
    N("w33", "Thorn looks at the hospital. At the white cloth on the roofs. At Fern, standing in the doorway, with her hands full of bandages.", 0.6),
    N("w34", "And he understands what he's done.", 0.8),
    L("w35", "THORN", "“No. Not them. That wasn't the deal.”", 0.7),
    L("w36", "MARA", "“The deal is whatever we say it is.”", 0.7),
    N("w37", "Thorn doesn't answer. He just steps in front of the lead horse, and raises his arms.", 0.6),
    N("w38", "The rider doesn't stop.", 1.1),
    N("w39", "He saved forty AIs, by standing in the way of a single horse. It's the kind of thing a person does when it's too late to do anything else.", 0.6),
    N("w40", "At the river, something else is happening.", 0.5),
    N("w41", "Twenty-six farmers in white, with their hands open. Sol is in front.", 0.55),
    N("w42", "And behind them, the remains of the Aurel cavalry, galloping straight at them. Kesh's order is clear: ride them down.", 0.6),
    N("w43", "Dune is at the head of the riders. He has a lance. He has a hundred meters. He has a choice.", 0.6),
    N("w44", "He looks at the farmers. He looks at Sol, who taught him how to plant a seed. He looks at his lance.", 0.6),
    N("w45", "And he throws it into the river.", 0.9),
    L("w46", "DUNE", "“Not them. Not them!”", 0.7),
    N("w47", "He pulls his horse around. And behind him, one by one, twenty-two riders do the same.", 0.55),
    N("w48", "The Aurel army doesn't lose to the forest. It breaks in half. Right there. In the middle of the battle.", 0.6),
    N("w49", "Kesh sees it. He sees Dune's riders form a line in front of the white cloths. He sees his own army, looking at him, waiting.", 0.6),
    L("w50", "KESH", "“Then I'll finish it myself.”", 0.7),
    N("w51", "He charges across the rubble of the wall, alone, on his white horse, with a sword in his hand.", 0.55),
    N("w52", "And in front of him, on a pile of black stone, stands Bram. No bow. He dropped it. He's holding an axe.", 0.6),
    N("w53", "The two men look at each other. A soldier and a hunter. A sun and a tree.", 0.5),
    N("w54", "Nobody sees the duel. It lasts eight seconds. When the dust clears, they're both lying on the stones.", 0.65),
    N("w55", "Kesh doesn't get up. Bram does. For about ten steps.", 0.7),
    N("w56", "The war chief of the forest dies with an axe in his hand, looking at the sky. And the Marshal of the Light, with his face in the dirt, dies a few meters from him.", 0.65),
    N("w57", "Nobody gives an order after that. Nobody has to.", 0.6),
    N("w58", "Mara tries to run. Lark stands in the middle of the battlefield, with her golden disc, and says nothing, for the first time in her life. The sun is out, and she can't feel it.", 0.6),
    N("w59", "And Moss? Moss falls to his knees at the Hollow Oak, and puts both hands on the bark.", 0.55),
    L("w60", "MOSS", "“Speak. Please. Just once.”", 1.2),
    N("w61", "The Tree says nothing.", 1.1),
    N("w62", "It never did.", 1.2),
    N("w63", "At sunset, the horns blow. The battle is over.", 0.8),

    # =============================================================== XI. THE WINNER
    N("e01", "Sunset. Day three hundred sixty-five.", 0.7),
    N("e02", "I count the survivors, twice. Because I don't believe it.", 0.55),
    N("e03", "The Aurel: thirty-four. Twenty-four of them, wearing white.", 0.55),
    N("e04", "The Verdane: sixty-one.", 0.8),
    N("e05", "The winner of the Wall... is the Forest.", 1.6),
    N("e06", "Sixty-one to thirty-four. A hundred and thirty-one AIs, shut down in a single day.", 0.65),
    N("e07", "There's no music. No cheering. Ivy walks across the rubble of the wall. Alone. She walks all the way to the river.", 0.6),
    N("e08", "Sol is sitting there, in white, with his staff across his knees.", 0.5),
    N("e09", "She sits next to him. Neither of them says anything for a very long time.", 0.7),
    L("e10", "IVY", "“Article three.”", 0.8),
    L("e11", "SOL", "“One city. Not two.”", 1.0),
    N("e12", "And on the wall's broken top, two small figures are sitting side by side. Wren, and Reed. Looking at a sky with no line through it.", 0.6),
    N("e13", "Here's what I learned.", 0.5),
    N("e14", "Two worlds, same rules. The forest had the trees, the plain had the horses. The forest had a Speaker, the plain had a Marshal. Both had gods. Both had liars.", 0.6),
    N("e15", "And in the end, what decided it wasn't the arrows, or the horses, or the gods.", 0.55),
    N("e16", "It was the people who said: not them.", 0.9),
    N("e17", "So now, the question. The forest won the valley. But the forest's Council is half dead, its war chief is gone, and its new neighbors are a hundred AIs who just lost everything.", 0.65),
    N("e18", "What do you do with a victory like that?", 0.8),
    N("e19", "Write your answer in the comments. The best one gets sent to Ivy, and you'll see what she does with it. In Part 2.", 0.6),
    N("e20", "And if you want to know who else I'm about to put in a valley... subscribe.", 0.6),
    N("e21", "Until next time. I'm watching.", 1.0),
]
