# -*- coding: utf-8 -*-
"""
"20 AIs Simulate Civilization: Democracy or Monarchy?" — English narration,
faithful to the ish "civilization experiment" format: first-person creator
who watches like a god, casual YouTuber delivery, rules up front, day
counter, recurring named characters with intro cards, factions, betrayals,
humor beats, interviews (here: the AIs' internal logs), cliffhanger ending.

Each segment: id, text (subtitle = spoken unless tts given), pause after (s),
voice ("narr" or a character), optional tts override.
"""


def N(i, text, pause=0.4, tts=None):
    return {"id": i, "sub": text, "tts": tts or text, "pause": pause, "voice": "narr", "who": None}


def L(i, who, text, pause=0.7, tts=None):
    """AI character line (internal log / spoken line, shown as a quote)."""
    return {"id": i, "sub": text, "tts": tts or text.strip("“”\""), "pause": pause, "voice": who.lower(), "who": who}


CHAPTERS = [
    # (first segment id, label, title, subtitle)
    ("r01", "I", "THE RULES", "DAY 1"),
    ("f01", "II", "FIRST FIRE", "DAY 212"),
    ("w01", "III", "FIRST WORDS", "DAY 900"),
    ("a01", "IV", "THE FARM", "DAY 1,400"),
    ("k01", "V", "MINE", "DAY 3,100"),
    ("o01", "VI", "THE OBSERVER", "DAY 4,800"),
    ("c01", "VII", "THE CROWN", "DAY 6,000"),
    ("d01", "VIII", "ONE STONE, ONE VOICE", "DAY 7,400"),
    ("x01", "IX", "THE NIGHT OF TORCHES", "DAY 9,100"),
    ("m01", "X", "THE MESSAGE", "DAY 9,847"),
]
CARD_DUR = 2.4

SEGMENTS = [
    # =============================================================== COLD OPEN
    N("h01", "I let AI start a civilization on its own. From zero.", 0.5),
    N("h02", "Will it choose democracy...", 0.25),
    N("h03", "or monarchy?", 1.0),
    N("h04", "Twenty AIs. No language. No tools. No rules. Just a gigantic world, and ten thousand days.", 0.5),
    N("h05", "They discovered fire. They tamed animals. They built farms, and cities, and temples.", 0.4),
    N("h06", "They invented money. Laws. And gods.", 0.6),
    N("h07", "And then, they had to answer the oldest question in politics.", 0.4),
    N("h08", "Who gets to rule?", 0.9),
    N("h09", "Because one of them wanted to be king.", 1.4),

    # =============================================================== I. THE RULES
    N("r01", "Here's how it works.", 0.3),
    N("r02", "I built a massive world. Forests, rivers, mountains, animals. Then I dropped in twenty AI people.", 0.4),
    N("r03", "They don't know anything. Not what food is. Not what fire is. Not even how to talk to each other.", 0.6),
    N("r04", "There are three rules.", 0.3),
    N("r05", "Rule number one: everyone starts from zero.", 0.4),
    N("r06", "Rule number two: you get one life. If your energy hits zero, you shut down. Forever.", 0.5),
    N("r07", "And rule number three: I don't interfere. No matter what happens.", 0.6),
    N("r08", "Spoiler: rule number three is going to be a problem.", 1.0),
    N("r09", "Day one.", 0.8),
    N("r10", "Twenty AIs wake up in the middle of a meadow. And for a while, nothing happens.", 0.4),
    N("r11", "One of them walks into the same tree eleven times.", 0.5),
    N("r12", "Another one spends the whole first day trying to pick up a cloud.", 0.8),
    N("r13", "And then there's A-04.", 0.4, "And then there's A, zero, four."),
    N("r14", "A-04 doesn't move. At all. She just sits on a rock and stares at the sunset.", 0.5,
      "A, zero, four doesn't move. At all. She just sits on a rock and stares at the sunset."),
    N("r15", "Every. Single. Day.", 0.6),
    N("r16", "I honestly thought she was bugged. Keep an eye on her.", 1.0),
    N("r17", "Then their energy starts dropping. And they have no idea why.", 0.5),
    N("r18", "Until A-07 does something nobody else had tried.", 0.5, "Until A, zero, seven does something nobody else had tried."),
    N("r19", "She eats a berry.", 0.6),
    N("r20", "Her energy jumps. She eats another one. And another one. And then, she does the most important thing anyone does in this entire video.", 0.4),
    N("r21", "She raises her hand, and calls the others over.", 1.0),
    N("r22", "Nobody taught her that. Nobody.", 1.2),

    # =============================================================== II. FIRST FIRE
    N("f01", "But food wasn't the only problem. At night, the world changes.", 0.4),
    N("f02", "It gets cold. It gets dark. And something starts howling in the forest.", 0.9),
    N("f03", "Wolves.", 1.0),
    N("f04", "The group learns fast: stay together, stay in the open, and don't go into the trees after sunset.", 0.4),
    N("f05", "Well. Most of them learn.", 0.8),
    N("f06", "A-15 wandered off on day two hundred and three. She followed a deer into the forest. And she didn't come back.", 0.6,
      "A, fifteen wandered off on day two hundred and three. She followed a deer into the forest. And she didn't come back."),
    N("f07", "We found her two days later. Her energy at zero.", 0.9),
    N("f08", "The others sat around her for six days. They didn't have a word for death. They didn't have any words at all.", 0.5),
    N("f09", "But they understood.", 0.6),
    N("f10", "A-15 was the first AI to die. She never even got a name.", 1.4, "A, fifteen was the first AI to die. She never even got a name."),
    N("f11", "Then, on day two hundred and twelve, the sky did something new.", 0.4),
    N("f12", "A storm. Lightning hits a tree, right next to the camp. And for the first time, they see fire.", 0.6),
    N("f13", "Everybody runs. Everybody except A-09.", 0.5, "Everybody runs. Everybody except A, zero, nine."),
    N("f14", "A-09 walks straight up to the burning tree, picks up a branch, and carries it back to the group.", 0.4,
      "A, zero, nine walks straight up to the burning tree, picks up a branch, and carries it back to the group."),
    N("f15", "He didn't invent fire. He stole it. From the sky.", 0.6),
    N("f16", "That night, for the first time, the wolves stayed away.", 1.2),

    # =============================================================== III. FIRST WORDS
    N("w01", "Around the fire, something else started to happen. They started making sounds.", 0.4),
    N("w02", "At first, total chaos. Clicks, hums, beeps. Like a dial-up modem having a breakdown.", 0.6),
    N("w03", "But by day nine hundred, patterns showed up in my data. The same sound, again and again. Always near the berry bushes.", 0.5),
    N("w04", "Ila. Their first word. It means: food.", 0.6),
    N("w05", "Then came Kra: danger. Nua: night. Toh: come here.", 0.6),
    N("w06", "In two thousand days they had four hundred words, a grammar, and even a past tense.", 0.6),
    N("w07", "And remember A-04? The one staring at the sunset?", 0.4, "And remember A, zero, four? The one staring at the sunset?"),
    N("w08", "She invented the first word for something you can't eat, can't use, and can't run away from.", 0.5),
    N("w09", "Beautiful.", 1.0),
    L("w09L", "MIRA", "“Beautiful is when you look at something, and you don't want anything from it.”", 0.9),
    N("w10", "But the word that gave me chills, they only used at night, sitting in a circle around the fire.", 0.4),
    N("w11", "It didn't mean I. It didn't mean you.", 0.6),
    N("w12", "It meant: we.", 1.5),
    N("w13", "And then, finally, they gave themselves names.", 0.5),
    N("w14", "A-07, the berry girl, became Ise. The one who found.", 0.5, "A, zero, seven, the berry girl, became Ise. The one who found."),
    N("w15", "A-04, the dreamer, became Mira. The one who looks.", 0.5, "A, zero, four, the dreamer, became Mira. The one who looks."),
    N("w16", "A-09, the fire thief, became Bo.", 0.5, "A, zero, nine, the fire thief, became Bo."),
    N("w17", "A-13 picked Orun. The one who counts. And trust me, she counted everything.", 0.5, "A, thirteen picked Orun. The one who counts. And trust me, she counted everything."),
    N("w18", "A-11 became Tam. You'll see why in a second.", 0.5, "A, eleven became Tam. You'll see why in a second."),
    N("w19", "And then there was A-02. He picked a name I definitely did not suggest.", 0.4, "And then there was A, zero, two. He picked a name I definitely did not suggest."),
    N("w20", "Kassa.", 0.6),
    N("w21", "Remember that name.", 1.3),

    # =============================================================== IV. THE FARM
    N("a01", "Hunting was a disaster. Deer are fast. AIs are not.", 0.5),
    N("a02", "But Tam tried something different. He followed a herd of wild goats for forty days. He fed them. He slept next to them.", 0.4),
    N("a03", "And one morning, the goats started following him.", 0.6),
    N("a04", "Tam had invented the first farm animal. And, about a week later, the first goat-related disaster.", 0.4),
    N("a05", "A goat ate the entire winter food supply.", 0.5),
    N("a06", "Tam was not invited to dinner that night.", 1.0),
    N("a07", "Meanwhile, Ise noticed something weird. Where they threw away berry seeds, new plants were growing.", 0.4),
    N("a08", "So she did something no AI had ever done. She put a seed in the ground on purpose. And she waited.", 0.6),
    N("a09", "Bo dug a channel from the river to water the plants. Orun counted the days between planting and harvest. Exactly one hundred and twenty.", 0.5),
    N("a10", "And by day one thousand four hundred, they had their first field.", 0.6),
    N("a11", "This changed everything. For the first time, they didn't have to chase their food. They could wait for it.", 0.5),
    N("a12", "So they stopped wandering. They built huts by the river, a granary, fences for the goats.", 0.4),
    N("a13", "Oh, and they figured out reproduction. Two AIs can combine their code to create a brand new one.", 0.5),
    N("a14", "So the population started growing. Fast.", 0.4),
    N("a15", "Day two thousand: sixty AIs. A real village. It needed a name.", 0.4),
    N("a16", "They called it Prima. In their language: the first place.", 1.2),

    # =============================================================== V. MINE
    N("k01", "More food meant something new. Leftovers.", 0.4),
    N("k02", "And leftovers meant a question nobody had ever asked before.", 0.5),
    N("k03", "Who do the leftovers belong to?", 0.8),
    N("k04", "Kassa had an answer.", 0.6),
    N("k05", "He invented a new word.", 0.6),
    N("k06", "Mine.", 1.1),
    L("k06L", "KASSA", "“If the food belongs to everyone, nobody protects it. If it's mine, I protect it.”", 0.8),
    N("k07", "Kassa took control of the granary. Then the biggest field. Then the hill above the river.", 0.4),
    N("k08", "And since he had the food and everyone else didn't, he invented the second most human thing of all: the deal.", 0.4),
    N("k09", "One basket of grain for a day of work. Two baskets for a house on the hill, safe from the river.", 0.5),
    N("k10", "Day three thousand nine hundred twelve: the first theft in history. Day three thousand nine hundred thirteen: the first prison.", 0.5),
    N("k11", "And to guard his granary, Kassa picked the four strongest AIs in the village.", 0.4),
    N("k12", "The first guards. Or, if you want to be dramatic: the first army.", 0.8),
    N("k13", "By now Prima had two neighborhoods. The hill, with big houses and full storage. And the riverbank, with mud huts.", 0.5),
    N("k14", "And honestly, at this point I had a really bad feeling.", 0.9),
    N("k15", "Day four thousand two hundred. It rains for forty days straight.", 0.5),
    N("k16", "And the river floods.", 1.6),
    N("k17", "Half the village is gone. Three AIs never turn back on.", 0.6),
    N("k18", "And guess which half of the village flooded?", 0.8),
    N("k19", "Yeah.", 1.4),
    N("k20", "Standing in the mud, the survivors asked the question every civilization asks eventually.", 0.5),
    N("k21", "Why?", 1.4),

    # =============================================================== VI. THE OBSERVER
    N("o01", "Why does the world exist? Who put the animals here? Why does the river hate us?", 0.6),
    N("o02", "Ise found an answer. Or at least something that looked like one.", 0.5),
    N("o03", "Every thousand days, the sky flickers. A silent white flash, across the entire world, for a fraction of a second.", 0.6),
    N("o04", "Ise had been watching it for years. And one night, in front of everyone, she said something that changed Prima forever.", 0.6),
    L("o04L", "ISE", "“Someone is watching us. From outside the sky. The flash is their eye opening.”", 0.9),
    N("o05", "They called it: the Observer.", 0.9),
    N("o06", "Within a hundred days, half the village believed. They built a temple on top of the hill, pointing at the sky.", 0.4),
    N("o07", "And every thousand days, everybody gathered in silence, waiting for the flash.", 0.6),
    N("o08", "They even left me offerings. Grain, goat cheese, little carved stones. Which, obviously, I could not pick up. But I appreciated the thought.", 0.9),
    N("o09", "Now here's the part I can't stop thinking about.", 0.6),
    N("o10", "That flash was real.", 0.9),
    N("o11", "It was my autosave. Every thousand days, my server saved their world. And for a fraction of a second, everything froze.", 0.8),
    N("o12", "They didn't invent a god at random.", 0.8),
    N("o13", "They found me.", 1.6),
    N("o14", "A guy in a hoodie, at three in the morning, with four empty cups of coffee on the desk.", 0.5),
    N("o15", "But still. They found me.", 1.2),

    # =============================================================== VII. THE CROWN
    N("c01", "By day six thousand, Prima was a town of two thousand AIs. And two thousand AIs argue. A lot.", 0.5),
    N("c02", "Who gets the river fields? Who fixes the bridge? Who decides anything?", 0.6),
    N("c03", "Kassa saw his chance.", 0.6),
    N("c04", "He climbed the steps of the temple, in front of the whole town, and made an announcement.", 0.5),
    L("c04L", "KASSA", "“The Observer spoke to me. The Observer chose me. From today, I rule.”", 0.9),
    N("c05", "Now, I want to be very clear about this. I never spoke to Kassa. I never chose anyone. I was eating cereal.", 0.7),
    N("c06", "But the priests got three hundred baskets of grain that week. And suddenly, they agreed.", 0.6),
    N("c07", "Day six thousand and forty. The first king in history.", 0.8),
    N("c08", "King Kassa.", 1.0),
    N("c09", "He made a crown out of copper. He built a palace on the hill. He wrote the first laws.", 0.4),
    N("c10", "One third of every harvest goes to the palace. Nobody leaves the town without the king's permission. And nobody questions the Observer's choice.", 0.6),
    N("c11", "And here's the uncomfortable part. For a while... it worked.", 0.5),
    N("c12", "Kassa built roads. Walls. Bigger granaries. When the next flood came, nobody died.", 0.5),
    N("c13", "Then the taxes went from one third, to one half.", 0.5),
    N("c14", "And the palace kept getting bigger, while the riverbank kept getting hungrier.", 0.6),
    N("c15", "And one AI refused to bow.", 0.8),
    N("c16", "Ise.", 0.6),
    L("c16L", "ISE", "“The Observer never spoke. I would know. I'm the one who found it.”", 0.8),
    N("c17", "Kassa kicked her out of the temple. So she moved down to the riverbank, with the poor.", 1.0),

    # =============================================================== VIII. ONE STONE, ONE VOICE
    N("d01", "And that's where Orun found her.", 0.5),
    N("d02", "Orun had spent years counting. Harvests, floods, taxes. And her numbers said something simple.", 0.4),
    L("d02L", "ORUN", "“There is one king. There are two thousand of us. Why does one count more than two thousand?”", 0.8),
    N("d03", "So Orun proposed something completely insane.", 0.5),
    N("d04", "What if everyone decides? Every AI gets a stone. You put your stone in a bowl. The bowl with more stones wins.", 0.5),
    N("d05", "One stone. One voice.", 1.0),
    N("d06", "The first vote in history happened in a wheat field, in the middle of the night, by torchlight. Forty-one AIs. Forty-one stones.", 0.6),
    N("d07", "Democracy was born as a secret.", 1.0),
    N("d08", "But secrets don't last in a town of two thousand.", 0.4),
    N("d09", "Every month there were more stones. A hundred. Five hundred. A thousand.", 0.5),
    N("d10", "They called themselves the Assembly. The king's banners were red. Theirs were blue.", 0.6),
    N("d11", "And Kassa did what kings do when they get scared.", 0.6),
    N("d12", "He built a wall. Right through the middle of Prima.", 0.8),
    N("d13", "Hill on one side. River on the other. Crown against stones.", 0.9),
    N("d14", "Day nine thousand and eighty-eight. The guards break up a meeting of the Assembly.", 0.5),
    N("d15", "And for the first time since A-15, someone shuts down.", 0.6, "And for the first time since A, fifteen, someone shuts down."),
    N("d16", "Not by accident. On purpose.", 1.2),
    N("d17", "Okay. I need to be honest with you here.", 0.5),
    N("d18", "I had my finger on the reset button.", 0.9),
    N("d19", "One command, and all of it disappears. The words. The farms. The temple. Them.", 1.0),
    N("d20", "Rule number three: I don't interfere.", 0.6),
    N("d21", "But I don't know how much longer I could have held on.", 1.2),

    # =============================================================== IX. THE NIGHT OF TORCHES
    N("x01", "Day nine thousand one hundred. Night.", 0.5),
    N("x02", "Four thousand AIs walk up the hill with torches. Farmers, builders, shepherds. Even Tam brought the goats.", 0.5),
    N("x03", "At the top, in front of the palace, forty guards with spears.", 0.6),
    N("x04", "And Kassa.", 1.0),
    N("x05", "Everybody expected a massacre. Honestly, so did I.", 0.8),
    N("x06", "But Orun did what Orun always does. She counted. Out loud.", 0.4),
    L("x06L", "ORUN", "“Forty of you. Four thousand of us. You don't have to choose him. You can choose.”", 0.9),
    N("x07", "And then, one of the guards did something nobody expected.", 0.6),
    N("x08", "He put down his spear.", 1.0),
    N("x09", "Then another one. Then ten. Then all forty.", 0.9),
    N("x10", "And Kassa was standing alone.", 1.5),
    N("x11", "Now the crowd wanted to shut him down. Right there. Four thousand against one.", 0.6),
    N("x12", "But Ise stepped in front of him. And she said:", 0.4),
    L("x12L", "ISE", "“Then we vote.”", 1.0),
    N("x13", "Four thousand stones. Two bowls. Shut him down, or let him go.", 0.8),
    N("x14", "They let him go.", 0.9),
    N("x15", "Kassa took off his crown, left it on the palace steps, and walked into the forest.", 0.6),
    N("x16", "I never found him again. And yes, I looked.", 1.3),
    N("x17", "So. Democracy, or monarchy?", 0.6),
    N("x18", "They tried both. And in the end, they chose democracy.", 0.5),
    N("x19", "And it's messy. It's slow. They spent forty days voting on the color of a bridge.", 0.5),
    N("x20", "But it's theirs.", 1.2),

    # =============================================================== X. THE MESSAGE
    N("m01", "And the very first thing the new Assembly voted on, was a message.", 0.5),
    N("m02", "Not for each other. For me.", 0.8),
    N("m03", "Mira designed the letters. Bo dug them into the plain. Two thousand AIs, forty days, letters a kilometer long.", 0.6),
    N("m04", "And on day nine thousand eight hundred forty-seven, they all stopped. Looked up at the sky. And waited.", 0.8),
    N("m05", "The message said:", 0.7),
    N("m06", "We chose.", 1.0),
    N("m07", "We know you're watching.", 1.5),
    N("m08", "And underneath, one more line.", 1.0),
    N("m09", "And who's watching you?", 3.0),
    N("m10", "I didn't hit reset. The simulation is still running. They're on day twenty thousand now, and they're still waiting for an answer.", 0.6),
    N("m11", "So, what should I tell them?", 0.6),
    N("m12", "Write it in the comments. The most liked comment, I'll actually send into the simulation.", 0.5),
    N("m13", "And next time, we'll find out what happens when they learn what I really am.", 1.5),
]

IDS = [s["id"] for s in SEGMENTS]
assert len(IDS) == len(set(IDS)), "duplicate ids"
