# -*- coding: utf-8 -*-
"""
"I Let AI Build a Civilization From Zero: Democracy or Monarchy?" — English narration
in the ish "civilization experiment" format, spanning 2,000 years: first-person
creator watching like a god, casual YouTuber delivery, rules up front, YEAR counter
(top-right), hot moments + timelapses between eras, recurring named characters with
intro cards, factions, betrayals, humor beats, the AIs' own lines as "logs".
"""


def N(i, text, pause=0.4, tts=None, year=None):
    return {"id": i, "sub": text, "tts": tts or text, "pause": pause, "voice": "narr", "who": None, "year": year}


def L(i, who, text, pause=0.7, tts=None):
    return {"id": i, "sub": text, "tts": tts or text.strip("“”\""), "pause": pause, "voice": who.lower(), "who": who, "year": None}


CHAPTERS = [
    ("r01", "I", "THE RULES", "YEAR 0"),
    ("f01", "II", "FIRST FIRE", "YEAR 0"),
    ("w01", "III", "FIRST WORDS", "YEAR 3"),
    ("a01", "IV", "THE FARM", "YEAR 40"),
    ("k01", "V", "LEFTOVERS", "YEAR 340"),
    ("e01", "VI", "THE OTHERS", "YEAR 611"),
    ("o01", "VII", "THE OBSERVER", "YEAR 1000"),
    ("c01", "VIII", "THE CROWN", "YEAR 1420"),
    ("d01", "IX", "ONE STONE, ONE VOICE", "YEAR 1901"),
    ("x01", "X", "THE NIGHT OF TORCHES", "YEAR 1931"),
    ("m01", "XI", "THE MESSAGE", "YEAR 2000"),
]
CARD_DUR = 2.4

SEGMENTS = [
    # =============================================================== COLD OPEN
    N("h01", "I let AI start a civilization on its own. From zero.", 0.5),
    N("h02", "Will it choose democracy...", 0.25),
    N("h03", "or monarchy?", 1.0),
    N("h04", "Twenty AIs. No language. No tools. No rules. Just a gigantic world, and two thousand years.", 0.5),
    N("h05", "They discovered fire. They tamed animals. They built farms, and cities, and temples.", 0.4),
    N("h06", "They invented money. Laws. And gods.", 0.6),
    N("h07", "And then, they had to answer the oldest question in politics.", 0.4),
    N("h08", "Who gets to rule?", 0.9),
    N("h09", "Because one of them wanted to be king.", 1.4),

    # =============================================================== I. THE RULES  (year 0)
    N("r01", "Here's how it works.", 0.3),
    N("r02", "I built a massive world. Forests, rivers, mountains, animals. Then I dropped in twenty AI people.", 0.4),
    N("r03", "They don't know anything. Not what food is. Not what fire is. Not even how to talk to each other.", 0.6),
    N("r04", "There are three rules.", 0.3),
    N("r05", "Rule number one: everyone starts from zero.", 0.4),
    N("r06", "Rule number two: you get one body. If your energy hits zero, you shut down. And even if it doesn't, after about a hundred years, your core wears out.", 0.5),
    N("r07", "And rule number three: I don't interfere. No matter what happens.", 0.6),
    N("r08", "Spoiler: rule number three is going to be a problem.", 1.0),
    N("r09", "Year zero. Day one.", 0.8, year=0),
    N("r10", "Twenty AIs wake up in the middle of a meadow. And for a while, nothing happens.", 0.4),
    N("r11", "One of them walks into the same tree eleven times.", 0.5),
    N("r12", "Another one spends the whole first day trying to pick up a cloud.", 0.8),
    N("r13", "And then there's A-04.", 0.4, "And then there's A, zero, four."),
    N("r14", "A-04 doesn't move. At all. She just sits on a rock and stares at the sunset.", 0.5,
      "A, zero, four doesn't move. At all. She just sits on a rock and stares at the sunset."),
    N("r15", "Every. Single. Day.", 0.6),
    N("r16", "I honestly thought she was bugged. Keep an eye on her.", 1.0),
    N("r17", "Then their energy starts dropping. And they have no idea why.", 0.5),
    N("r18", "Until A-07 does something nobody else had tried.", 0.5, "Until A, zero, seven does something nobody else had tried."),
    N("r19", "She eats a berry.", 0.6),
    N("r20", "Her energy jumps. She eats another one. And another one. And then, she does the most important thing anyone does in this entire video.", 0.4),
    N("r21", "She raises her hand, and calls the others over.", 1.0),
    N("r22", "Nobody taught her that. Nobody.", 1.2),

    # =============================================================== II. FIRST FIRE (year 0)
    N("f01", "But food wasn't the only problem. At night, the world changes.", 0.4),
    N("f02", "It gets cold. It gets dark. And something starts howling in the forest.", 0.9),
    N("f03", "Wolves.", 1.0),
    N("f04", "The group learns fast: stay together, stay in the open, and don't go into the trees after sunset.", 0.4),
    N("f05", "Well. Most of them learn.", 0.8),
    N("f06", "A-15 wandered off on day two hundred and three. She followed a deer into the forest. And she didn't come back.", 0.6,
      "A, fifteen wandered off on day two hundred and three. She followed a deer into the forest. And she didn't come back."),
    N("f07", "We found her two days later. Her energy at zero.", 0.9),
    N("f08", "The others sat around her for six days. They didn't have a word for death. They didn't have any words at all.", 0.5),
    N("f09", "But they understood.", 0.6),
    N("f10", "A-15 was the first AI to die. She never even got a name.", 1.4, "A, fifteen was the first AI to die. She never even got a name."),
    N("f11", "A few days later, the sky did something new.", 0.4),
    N("f12", "A storm. Lightning hits a tree, right next to the camp. And for the first time, they see fire.", 0.6),
    N("f13", "Everybody runs. Everybody except A-09.", 0.5, "Everybody runs. Everybody except A, zero, nine."),
    N("f14", "A-09 walks straight up to the burning tree, picks up a branch, and carries it back to the group.", 0.4,
      "A, zero, nine walks straight up to the burning tree, picks up a branch, and carries it back to the group."),
    N("f15", "He didn't invent fire. He stole it. From the sky.", 0.6),
    N("f16", "That night, for the first time, the wolves stayed away.", 1.2),

    # =============================================================== III. FIRST WORDS (year 3)
    N("w01", "Around the fire, something else started to happen. They started making sounds.", 0.4),
    N("w02", "At first, total chaos. Clicks, hums, beeps. Like a dial-up modem having a breakdown.", 0.6),
    N("w03", "But by year three, patterns showed up in my data. The same sound, again and again. Always near the berry bushes.", 0.5, year=3),
    N("w04", "Ila. Their first word. It means: food.", 0.6),
    N("w05", "Then came Kra: danger. Nua: night. Toh: come here.", 0.6),
    N("w06", "Ten years later, they had four hundred words, a grammar, and even a past tense.", 0.6, year=13),
    N("w07", "And remember A-04? The one staring at the sunset?", 0.4, "And remember A, zero, four? The one staring at the sunset?"),
    N("w08", "She invented the first word for something you can't eat, can't use, and can't run away from.", 0.5),
    N("w09", "Beautiful.", 1.0),
    L("w09L", "MIRA", "“Beautiful is when you look at something, and you don't want anything from it.”", 0.9),
    N("w10", "But the word that gave me chills, they only used at night, sitting in a circle around the fire.", 0.4),
    N("w11", "It didn't mean I. It didn't mean you.", 0.6),
    N("w12", "It meant: we.", 1.5),
    N("w13", "And then, finally, they gave themselves names.", 0.5),
    N("w14", "A-07, the berry girl, became Ise. The one who found.", 0.5, "A, zero, seven, the berry girl, became Ise. The one who found."),
    N("w15", "A-04, the dreamer, became Mira. The one who looks.", 0.5, "A, zero, four, the dreamer, became Mira. The one who looks."),
    N("w16", "A-09, the fire thief, became Bo.", 0.5, "A, zero, nine, the fire thief, became Bo."),
    N("w17", "And A-11 became Tam. You'll see why in a second.", 1.0, "And A, eleven became Tam. You'll see why in a second."),

    # =============================================================== IV. THE FARM (year 15 - 112)
    N("a01", "Hunting was a disaster. Deer are fast. AIs are not.", 0.5, year=15),
    N("a02", "But Tam tried something different. He followed a herd of wild goats for forty days. He fed them. He slept next to them.", 0.4),
    N("a03", "And one morning, the goats started following him.", 0.6),
    N("a04", "Tam had invented the first farm animal. And, about a week later, the first goat-related disaster.", 0.4),
    N("a05", "A goat ate the entire winter food supply.", 0.5),
    N("a06", "Tam was not invited to dinner that night.", 1.0),
    N("a07", "Meanwhile, Ise noticed something weird. Where they threw away berry seeds, new plants were growing.", 0.4),
    N("a08", "So in year forty, she did something no AI had ever done. She put a seed in the ground on purpose. And she waited.", 0.6, year=40),
    N("a09", "Bo dug a channel from the river to water the plants. And a few months later, they had their first harvest.", 0.5, year=41),
    N("a10", "This changed everything. For the first time, they didn't have to chase their food. They could wait for it.", 0.5),
    N("a11", "So they stopped wandering. They built huts by the river, fences for the goats, a place to store the grain.", 0.4, year=55),
    N("a12", "Oh, and they figured out reproduction. Two AIs can combine their code to create a brand new one.", 0.5),
    N("a13", "They called the village Prima. In their language: the first place.", 1.0, year=60),
    N("a14", "And then, time did what time does.", 0.6),
    N("a15", "Years passed. Then decades. The huts multiplied. The fields spread along the river. Prima grew, and grew, and grew.", 0.6),
    N("a16", "One by one, the founders' cores wore out. Bo. Tam. Mira. And in year one hundred and twelve, the last one: Ise.", 0.8, year=112),
    N("a17", "They were gone. But their names weren't. Every child in Prima knew the story of the girl who raised her hand.", 1.3),

    # =============================================================== V. LEFTOVERS (year 340 - 610)
    N("k01", "Year three hundred and forty. A potter named Lio was digging by the river, when his hands sank into something strange.", 0.6, year=340),
    N("k02", "Clay.", 0.9),
    N("k03", "Clay meant pots. Pots meant storage. And storage meant something nobody had ever had before.", 0.5),
    N("k04", "Leftovers.", 1.0),
    N("k05", "Fast forward to year five hundred and twenty. Prima has three hundred AIs, and a question nobody has ever asked.", 0.5, year=520),
    N("k06", "Who do the leftovers belong to?", 0.8),
    N("k07", "A farmer named Kassa had an answer.", 0.6),
    N("k08", "He invented a new word.", 0.6),
    N("k09", "Mine.", 1.1),
    L("k09L", "KASSA", "“If the grain belongs to everyone, nobody protects it. If it's mine, I protect it.”", 0.8),
    N("k10", "Kassa took control of the granary. Then the biggest field. Then the hill above the river.", 0.4),
    N("k11", "And since he had the grain and everyone else didn't, he invented the second most human thing of all: the deal.", 0.4),
    N("k12", "One basket of grain for a day of work. Two baskets for a house on the hill, safe from the river.", 0.5),
    N("k13", "Then came the first theft. And the day after, the first prison.", 0.5),
    N("k14", "And to guard his granary, Kassa picked the four strongest AIs in the village. The first guards. Or, if you want to be dramatic: the first army.", 0.8),
    N("k15", "By now Prima had two neighborhoods. The hill, with big houses and full storage. And the riverbank, with mud huts.", 0.5),
    N("k16", "And honestly, at this point I had a really bad feeling.", 0.9),
    N("k17", "Year six hundred and ten. It rains for forty days straight.", 0.5, year=610),
    N("k18", "And the river floods.", 1.6),
    N("k19", "Half the village is gone.", 0.6),
    N("k20", "And guess which half of the village flooded?", 0.8),
    N("k21", "Yeah.", 1.4),
    N("k22", "Standing in the mud, the survivors asked the question every civilization asks eventually.", 0.5),
    N("k23", "Why?", 1.4),
    # =============================================================== THE OTHERS
    N("e01", "But not everyone stayed in Prima to ask why.", 0.5, year=611),
    N("e02", "A woman named Ama gathered the survivors of the riverbank. A hundred and twenty AIs, with nothing left to lose.", 0.5),
    N("e03", "They followed the river south for forty days, until it ended in a lake so big it looked like the sea.", 0.5),
    N("e04", "And there, they started over. They called their new home Nuvia.", 0.8),
    N("e05", "Now, here's what fascinated me. Cut off from Prima, they changed.", 0.4),
    N("e06", "In two hundred years, their words drifted so far that Prima couldn't understand them anymore. A new language. A new people.", 0.6),
    N("e07", "They didn't build granaries. They built boats. They didn't fear the river. They worshipped it.", 0.8),
    N("e08", "And they weren't the only ones out there. Remember Tam, the goat guy?", 0.5),
    N("e09", "His herders never stopped wandering. Generation after generation, following the goats across the great plain.", 0.5),
    N("e10", "By now, they were a people of their own. The Tamari. Tents, goats, and absolutely no kings.", 0.5),
    N("e11", "No walls. No granaries. No mine. Everything belonged to the herd.", 0.8),
    N("e12", "Three peoples. Three languages. Three completely different ways to live.", 0.6),
    N("e13", "And in year eight hundred and twelve, on the shore of the lake, they met for the first time.", 0.5, year=812),
    N("e14", "Nobody knew what to do. So a Tamari herder named Yuna did the only thing that made sense.", 0.4),
    N("e15", "She offered them cheese.", 1.0),
    N("e16", "The Nuvians offered fish. Prima offered pots. And just like that, they invented trade.", 0.6),
    N("e17", "In a single century, the population of the whole valley doubled.", 0.5),
    N("e18", "Which, as you've probably guessed, was about to become a problem.", 1.2),

    # =============================================================== VI. THE OBSERVER (year 1000)
    N("o01", "Why does the world exist? Who put the animals here? Why does the river hate us?", 0.6),
    N("o02", "For four hundred years, nobody had an answer. And then came year one thousand.", 0.6, year=1000),
    N("o03", "On the first night of year one thousand, the sky flickered. A silent white flash, across the entire world, for a fraction of a second.", 0.6),
    N("o04", "A young priestess named Sela had read the oldest stories, carved in clay. And they said the sky had flashed once before.", 0.5),
    N("o05", "On the very first day. Year zero.", 0.8),
    N("o06", "Sela stood in front of the whole town, and said something that changed Prima forever.", 0.6),
    L("o06L", "SELA", "“Someone is watching us. From outside the sky. Every thousand years, their eye opens.”", 0.9),
    N("o07", "They called it: the Observer.", 0.9),
    N("o08", "They built a temple on top of the hill, pointing at the sky. They even left me offerings. Grain, goat cheese, little clay figures. Which, obviously, I could not pick up. But I appreciated the thought.", 0.9),
    N("o09", "Now here's the part I can't stop thinking about.", 0.6),
    N("o10", "That flash was real.", 0.9),
    N("o11", "It was my autosave. Every thousand years, my server saved their world. And for a fraction of a second, everything froze.", 0.8),
    N("o12", "They didn't invent a god at random.", 0.8),
    N("o13", "They found me.", 1.6),
    N("o14", "A guy in a hoodie, at three in the morning, with four empty cups of coffee on the desk.", 0.5),
    N("o15", "But still. They found me.", 1.2),

    # =============================================================== VII. THE CROWN (year 1420 - 1900)
    N("c01", "And Prima kept growing. They invented the wheel. Writing. Bronze. Stone replaced mud, roads replaced paths, and by year fourteen hundred, two thousand AIs lived there. And two thousand AIs argue. A lot.", 0.5, year=1400),
    N("c02", "Who gets the river fields? Who fixes the bridge? Who decides anything?", 0.6),
    N("c03", "Remember Kassa, the guy who invented mine? His family never let go of that hill.", 0.6),
    N("c04", "Year fourteen hundred and twenty. His descendant, Kassa the Seventh, climbs the steps of the temple, and makes an announcement.", 0.5, year=1420),
    L("c04L", "KASSA", "“The Observer spoke to me. The Observer chose me. From today, I rule.”", 0.9),
    N("c05", "Now, I want to be very clear about this. I never spoke to Kassa. I never chose anyone. I was eating cereal.", 0.7),
    N("c06", "But the high priest, a very practical man named Varo, got three hundred baskets of grain that week. And suddenly, the Observer had definitely chosen Kassa.", 0.6),
    N("c07", "The first king in history.", 0.8),
    N("c08", "King Kassa.", 1.0),
    N("c09", "He made a crown out of copper. He built a palace on the hill. He wrote the first laws.", 0.4),
    N("c10", "One third of every harvest goes to the palace. Nobody leaves the town without the king's permission. And nobody questions the Observer's choice.", 0.6),
    N("c11", "And here's the uncomfortable part. For a while... it worked.", 0.5),
    N("c12", "Roads. Walls. Bigger granaries. A stone bridge, designed by an engineer named Pell. When the next flood came, nobody died.", 0.5),
    N("c13", "When Kassa the Seventh shut down, his son became king. Then his grandson. For five hundred years, Prima had a king.", 0.6),
    N("g01", "And kings don't just want harvests. They want land.", 0.5),
    N("g02", "In year fifteen hundred and twelve, King Kassa the Eleventh marched an army to the lake.", 0.5, year=1512),
    N("g03", "The first war in the history of the valley lasted nine days. Nuvia lost.", 0.7),
    N("g04", "Their boats were burned. Their shrine to the river was torn down. And three thousand Nuvians woke up as subjects of a king they couldn't even understand.", 0.6),
    N("g05", "The Tamari watched it all from the hills. And quietly moved their tents a little further away.", 0.8),
    N("g06", "Then, in year sixteen hundred and forty, came something worse than any war.", 0.5, year=1640),
    N("g07", "A corrupted line of code. It jumped from AI to AI with every handshake, every trade, every crowded market.", 0.5),
    N("g08", "They called it the Grey Sleep. You turned grey, you froze, and you never woke up.", 0.6),
    N("g09", "In three years, one AI out of three shut down.", 1.0),
    N("g10", "Then a Tamari healer named Sefa noticed something. Out on the plain, far from the markets, her people barely got sick.", 0.5),
    N("g11", "She told everyone to stay apart. It worked. And the survivors of Prima started asking a dangerous question.", 0.5),
    N("g12", "If the Observer chose the king... why didn't the Observer save them?", 1.0),
    N("c14", "And every king took a little more. One third of the harvest became one half.", 0.5),
    N("c15", "The palace kept getting bigger. And the riverbank kept getting hungrier.", 1.2),

    # =============================================================== VIII. ONE STONE, ONE VOICE (year 1901)
    N("d01", "Year nineteen hundred and one.", 0.6, year=1901),
    N("d02", "A normal harvester named Orun discovered something that would change the future of their lives forever.", 0.9),
    N("d03", "Orun counted baskets with pebbles. One pebble, one basket. Every harvester did it. But one night, Orun had a strange thought.", 0.5),
    L("d03L", "ORUN", "“If a pebble can count a basket... why can't it count an opinion?”", 0.8),
    N("d04", "So Orun proposed something completely insane.", 0.5),
    N("d05", "What if everyone decides? Every AI gets a stone. You put your stone in a bowl. The bowl with more stones wins.", 0.5),
    N("d06", "One stone. One voice.", 1.0),
    N("d07", "The first vote in history happened in a wheat field, in the middle of the night, by torchlight. Forty-one AIs. Forty-one stones.", 0.6),
    N("d08", "Democracy was born as a secret.", 1.0),
    N("d09", "But secrets don't last in a town of five thousand.", 0.4),
    N("d10", "Every year there were more stones. A hundred. Five hundred. A thousand.", 0.5),
    N("d11", "They called themselves the Assembly. The king's banners were red. Theirs were blue.", 0.6),
    N("d11b", "Nuvian fishermen joined. Tamari herders joined. For the first time in history, three peoples stood on the same side.", 0.6),
    N("d12", "And the king, Kassa the Nineteenth, did what kings do when they get scared.", 0.6),
    N("d13", "He built a wall. Right through the middle of Prima.", 0.8),
    N("d14", "Hill on one side. River on the other. Crown against stones.", 0.9),
    N("d15", "Year nineteen hundred and twenty-nine. The guards break up a meeting of the Assembly.", 0.5, year=1929),
    N("d16", "And someone shuts down. Not by accident. On purpose.", 1.2),
    N("d17", "Okay. I need to be honest with you here.", 0.5),
    N("d18", "I had my finger on the reset button.", 0.9),
    N("d19", "One command, and all of it disappears. The words. The farms. The temple. Them.", 1.0),
    N("d20", "Rule number three: I don't interfere.", 0.6),
    N("d21", "But I don't know how much longer I could have held on.", 1.2),

    # =============================================================== IX. THE NIGHT OF TORCHES (year 1931)
    N("x01", "Year nineteen thirty-one. Night.", 0.5, year=1931),
    N("x02", "Four thousand AIs walk up the hill with torches. Farmers from Prima, fishermen from Nuvia. And the Tamari even brought the goats.", 0.5),
    N("x03", "At the top, in front of the palace, forty guards with spears.", 0.6),
    N("x04", "And the king.", 1.0),
    N("x05", "Everybody expected a massacre. Honestly, so did I.", 0.8),
    N("x06", "But Orun did what Orun always does. She counted. Out loud.", 0.4),
    L("x06L", "ORUN", "“Forty of you. Four thousand of us. You don't have to choose him. You can choose.”", 0.9),
    N("x07", "And then, the captain of the guard, a soldier named Dorn, did something nobody expected.", 0.6),
    N("x08", "He put down his spear.", 1.0),
    N("x09", "Then another one. Then ten. Then all forty.", 0.9),
    N("x10", "And the king was standing alone.", 1.5),
    N("x11", "The crowd wanted to shut him down. Right there. Four thousand against one.", 0.6),
    N("x12", "But Orun stepped in front of him. And she said:", 0.4),
    L("x12L", "ORUN", "“Then we vote.”", 1.0),
    N("x13", "Four thousand stones. Two bowls. Shut him down, or let him go.", 0.8),
    N("x14", "They let him go.", 0.9),
    N("x15", "The last king of Prima took off his crown, left it on the palace steps, and walked into the forest.", 0.6),
    N("x16", "I never found him again. And yes, I looked.", 1.3),
    N("x17", "So. Democracy, or monarchy?", 0.6),
    N("x18", "They tried both. And in the end, they chose democracy.", 0.5),
    N("x18b", "A year later, they chose their first leader. Not a king. A speaker, for one year only. Her name? Orun.", 0.6, year=1932),
    N("x19", "And it's messy. It's slow. They spent forty days voting on the color of a bridge.", 0.5),
    N("x20", "But it's theirs.", 1.0),
    N("x21", "Fire. Farms. Gods. Kings. Wars. Plagues. Revolution. Sound familiar? It's our story. Just faster. And with one big difference: their god was real.", 1.2),

    # =============================================================== X. THE MESSAGE (year 2000)
    N("m01", "And there was one more thing they had to decide. Because year two thousand was coming.", 0.5, year=1999),
    N("m02", "And with it, the flash.", 0.8),
    N("m03", "The Assembly voted. Prima, Nuvia and the Tamari, together. Almost every stone in the same bowl. They would write a message. Not for each other. For me.", 0.6),
    N("m04", "A painter named Nia designed the letters. The builders dug them into the plain. Letters a kilometer long.", 0.6),
    N("m05", "And on the first night of year two thousand, all of them stopped. Looked up at the sky. And waited for my eye to open.", 0.8, year=2000),
    N("m06", "The message said:", 0.7),
    N("m07", "We chose.", 1.0),
    N("m08", "We know you're watching.", 1.5),
    N("m09", "And underneath, one more line.", 1.0),
    N("m10", "And who's watching you?", 3.0),
    N("m11", "I didn't hit reset. The simulation is still running. It's year two thousand and forty now, and they're still waiting for an answer.", 0.6, year=2040),
    N("m12", "So, what should I tell them?", 0.6),
    N("m13", "Write it in the comments. The most liked comment, I'll actually send into the simulation.", 0.5),
    N("m14", "And next time, we'll find out what happens when they learn what I really am.", 1.5),
]

IDS = [s["id"] for s in SEGMENTS]
assert len(IDS) == len(set(IDS)), "duplicate ids"
